---

- name: Converge
  hosts: all
  become: "yes"
  roles:
    - deitkrachten.gnome_desktop
  tasks:
    - name: Include role 'ansible-role-lens'
      ansible.builtin.include_role:
        name: ansible-role-lens
